name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build Go app
        run: |
          go mod tidy
          go build -o go-app .

      - name: Create zip and tar.gz files
        run: |
          zip go-app.zip go-app
          tar -czf go-app.tar.gz go-app

      - name: Build Docker image
        run: |
          docker build -t go-app:latest .

      - name: Push Docker image to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: Nava200
          password: ${{ secrets.PTA }}  # Use the correct case-sensitive secret name
          registry: ghcr.io

      - name: Tag and push Docker image
        run: |
          docker tag go-app:latest ghcr.io/Nava200/go-app:latest
          docker push ghcr.io/Nava200/go-app:latest
